import Head from 'next/head'

import Profile from '../components/Profile'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Profile/>
    </>
  )
}
